### ISSUE TITLE
Period and full cycle

### ISSUE THREAD

**Issue by palimondo** [lemire/SwiftWyhash#10]
If I understand correctly, you have tested `wyhash64` and `wyrand` [PRNG with BigCrunch and PractRand](https://github.com/lemire/testingRNG). It looks like the whole [wyhash](https://github.com/wangyi-fudan/wyhash) is still in flux (the hashing function was remixed earlier today, RNG unchanged), but I'm particularly interested in the [concern raised by a critic in their Issue # 15](https://github.com/wangyi-fudan/wyhash/issues/15#issuecomment-500254119):
> Besides, wyrand() is also of some concern.
> 
> Briefly, it accepts any 64-bit value as a seed. Therefore, it should be analytically (since there is no other way) proven that the generator period is 2^64.
> 
> Otherwise, with some custom seed, the generator can get into an unacceptably short ring. Alternatively, it is sufficient to prove that the generator has no rings shorter than some acceptable period (i.e. 2^48).

I have briefly searched for PRNG periods, but so far I only found this [Stack Exchange Security answer](https://security.stackexchange.com/a/54550) and a discussion about [full cycle](https://en.wikipedia.org/wiki/Full_cycle) on Wikipedia:
> The restrictions on the parameters of a PRNG for it to possess a full cycle are known only for certain types of PRNGs, such as linear congruential generators and linear feedback shift registers. There is no general method to determine whether a PRNG algorithm is full-cycle short of exhausting the state space, which may be exponentially large compared to the size of the algorithm's internal state.

Given that `wyrand`'s internal state is modified only by overflowing addition of the prime `0xa0761d6478bd642f`, what does this mean for period and cycle? Can this generator have short rings given a bad seed?

**Comment by lemire** [comment]
The number is even (0xa0761d6478bd642)... it is not prime.

The period of the state is going to be 2^63.

**Comment by palimondo** [comment]
It is a prime, see [WolframAlpha](https://www.wolframalpha.com/input/?i=Is+0xa0761d6478bd642f+a+prime%3F). (You forgot the last hexadecimal digit `f` somewhere along the way.)

All his new magic constants are primes that have [32 ones and 32 zeros in them](https://github.com/lemire/SwiftWyhash/issues/6#issuecomment-496830439).

**Comment by palimondo** [comment]
Can you explain (or a pointer to explanation would be helpful) why is the period of overflowing addition of even number 63-bits? And I'm assuming the period of overflowing addition of odd number would be 64-bit? I'm apparently struggling to develop a correct intuition for overflowing addition.

I've also read something about the period length of [MCG and LCG on O'Neill's blog](http://www.pcg-random.org/posts/does-it-beat-the-minimal-standard.html#todays-32-bit-minimal-standard-a-96-bit-truncated-lcg-or-mcg).

**Comment by lemire** [comment]
Suppose the period is P then P times your prime must be divisible by 2^64. Correct?

**Comment by palimondo** [comment]
🤷‍♂️

**Comment by lemire** [comment]
Let me call the prime p.

What is (p+p) with overflow?  It is actually the least significant 64 bits of 2p=p+p.

The "overflow" thing only means that you lose the most significant bits...

so p+p+p is 3p... with overflow, you just select the least significant 64 bits...  and so forth.

So suppose you start at "s"... you have s+p, s+2p, s+3p... where, when I write s+3p I mean just the least significant 64 bits of s+3p...

What will you come back to s? When s + P*p = s or when P*p = 0.

Does this help?

**Comment by palimondo** [comment]
Yes, but what guarantees that the least significant 64 bits in that series do not repeat for 2^64 iterations? Given that the prime is odd, the succession of sums will alternate between odd and even numbers. I played with the sequence in REPL like this:
````swift
(swift) let p1:UInt64 = 0xa0761d6478bd642f 
// p1 : UInt64 = 11562461410679940143
(swift) Array(sequence(first: 0, next: { $0 &+ p1 }).prefix(4))
// r0 : Array<UInt64> = [0, 11562461410679940143, 4678178747650328670, 16240640158330268813]
(swift) Array(sequence(first: 1, next: { $0 &+ p1 }).prefix(4))
// r1 : Array<UInt64> = [1, 11562461410679940144, 4678178747650328671, 16240640158330268814]
(swift) Array(sequence(first: 0 &- p1, next: { $0 &+ p1 }).prefix(4))
// r2 : Array<UInt64> = [6884282663029611473, 0, 11562461410679940143, 4678178747650328670]
(swift) Array(sequence(first: 0 &- p1 &- p1, next: { $0 &+ p1 }).prefix(4))
// r3 : Array<UInt64> = [13768565326059222946, 6884282663029611473, 0, 11562461410679940143]
````

I see that the initial value of the seed only shifts the additive sequence by that constant value. I see that overflowing subtraction is inverse operation… but I'm not sure what that all means for the period length and why there are no shorter rings than the full 64-bit period.

Does the prime addition form some kind of odd counter on the least significant X bits that uniquely maps to 2^X numbers before wrapping around?

````swift
Array(sequence(first: 0, next: { $0 &+ UInt8(3) }).prefix(258))
// r6 : Array<UInt8> = [0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99, 102, 105, 108, 111, 114,
117, 120, 123, 126, 129, 132, 135, 138, 141, 144, 147, 150, 153, 156, 159, 162, 165, 168,
171, 174, 177, 180, 183, 186, 189, 192, 195, 198, 201, 204, 207, 210, 213, 216, 219, 222,
225, 228, 231, 234, 237, 240, 243, 246, 249, 252, 255, 2, 5, 8, 11, 14, 17, 20, 23, 26,
29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59, 62, 65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 95,
98, 101, 104, 107, 110, 113, 116, 119, 122, 125, 128, 131, 134, 137, 140, 143, 146, 149,
152, 155, 158, 161, 164, 167, 170, 173, 176, 179, 182, 185, 188, 191, 194, 197, 200, 203,
206, 209, 212, 215, 218, 221, 224, 227, 230, 233, 236, 239, 242, 245, 248, 251, 254, 1, 4,
7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70, 73,
76, 79, 82, 85, 88, 91, 94, 97, 100, 103, 106, 109, 112, 115, 118, 121, 124, 127, 130, 133,
136, 139, 142, 145, 148, 151, 154, 157, 160, 163, 166, 169, 172, 175, 178, 181, 184, 187,
190, 193, 196, 199, 202, 205, 208, 211, 214, 217, 220, 223, 226, 229, 232, 235, 238,
241, 244, 247, 250, 253, 0, 3]
````
So this is counting up by 3 and shifting down by one when it overflows… 
 
I've also tried with largest prime < 256, `251` and it looks like countdown by 5, five times, shifting by one when it overflows… So I see that it works. But I still don't have a firm grasp of the why? It's 4am here, so I should definitely sleep on it. Maybe it'll be clearer in the morning! 😝😴

But given all this, I'd say `wyrand` is full cycle, with period of 2^64 and @leo-yuriev was incorrect in suspecting a possibility of short rings. Maybe he incorrectly assumed that the previous result is mixed back into seed like the [other implementers of `wyhash` were](https://github.com/cocowalla/wyhash-dotnet/issues/1)... and that would probably make it impossible to reason about the cycles analytically.

**Comment by lemire** [comment]
Slow down. Do you believe me that the period P must be such that p * P = 0 (in the last 64 bits) where p is the prime. Do you believe this fact?

**Comment by erthink** [comment]
I reformatted the code and looked it up.
```
static inline uint64_t wyrand(uint64_t *seed) {
  *seed += _wyp0;
  return _wymum(*seed ^ _wyp1, *seed);
}
```
It is obvious that the period is 2^64, since _wyp0 == 11562461410679940143 (0xa0761d6478bd642f) is prime.

Don't know where I was looking the first time, but my suspicions about `wyrand()` are completely unreasonable.
@wangyi-fudan, please excuse my inattention.

**Comment by lemire** [comment]
@leo-yuriev Nitpicking: does not need to prime, it merely needs to be odd.

**Comment by palimondo** [comment]
@lemire:
> Slow down. Do you believe me that the period P must be such that p * P = 0 (in the last 64 bits) where p is the prime. Do you believe this fact?

I believe all you tell me, but I am obviously missing some fundamental concept here… I'll self study further. Thank you for your patience and generosity, Daniel!

**Comment by lemire** [comment]
@palimondo Ok. If you'd like, we can continue this by email: lemire@gmail.com.
